name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 8
          - php: 7.3
            laravel: 8.*
            testbench: 6.*
          - php: 7.4
            laravel: 8.*
            testbench: 6.*
          - php: 8.0
            laravel: 8.*
            testbench: 6.*
          - php: 8.1
            laravel: 8.*
            testbench: 6.*
            
          # Laravel 9
          - php: 8.0
            laravel: 9.*
            testbench: 7.*
          - php: 8.1
            laravel: 9.*
            testbench: 7.*
          - php: 8.2
            laravel: 9.*
            testbench: 7.*
            
          # Laravel 10
          - php: 8.1
            laravel: 10.*
            testbench: 8.*
          - php: 8.2
            laravel: 10.*
            testbench: 8.*
          - php: 8.3
            laravel: 10.*
            testbench: 8.*
            
          # Laravel 11
          - php: 8.2
            laravel: 11.*
            testbench: 9.*
          - php: 8.3
            laravel: 11.*
            testbench: 9.*
            
          # Laravel 12 (future)
          - php: 8.3
            laravel: 12.*
            testbench: 10.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, json
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        run: vendor/bin/phpunit